name: todo_demo_flutter_redux
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  redux: ^2.1.1
  flutter_redux: ^0.4.0
  uuid: ^0.5.0

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
